

Set<String> characterNamesList = {
  "alisa",
  "anna",
  "armor-king",
  "asuka",
  "azucena",
  "bryan",
  "claudio",
  "clive",
  "devil-jin",
  "dragunov",
  "eddy",
  "fahkumram",
  "feng",
  "heihachi",
  "hwoarang",
  "jack-8",
  "jin",
  "jun",
  "kazuya",
  "king",
  "kuma",
  "lars",
  "law",
  "lee",
  "leo",
  "leroy",
  "lidia",
  "lili",
  "miary-zo",
  "nina",
  "panda",
  "paul",
  "raven",
  "reina",
  "shaheen",
  "steve",
  "victor",
  "xiaoyu",
  "yoshimitsu",
  "zafina"
};

List<Map<String, dynamic>> stances = [
  {'characterName': 'alisa', 'name': 'DES'},
  {'characterName': 'alisa', 'name': 'SBT'},
  {'characterName': 'alisa', 'name': 'DBT'},
  {'characterName': 'alisa', 'name': 'BKP'},
  {'characterName': 'anna', 'name': 'HMC'},
  {'characterName': 'anna', 'name': 'CJM'},
  {'characterName': 'anna', 'name': 'PLT'},
  {'characterName': 'armor-king', 'name': 'BJ'},
  {'characterName': 'armor-king', 'name': 'BAD'},
  {'characterName': 'asuka', 'name': 'NWG'},
  {'characterName': 'azucena', 'name': 'LIB'},
  {'characterName': 'azucena', 'name': 'BT'},
  {'characterName': 'bryan', 'name': 'SNE'},
  {'characterName': 'bryan', 'name': 'SWA'},
  {'characterName': 'bryan', 'name': 'CD'},
  {'characterName': 'claudio', 'name': 'STB'},
  {'characterName': 'clive', 'name': 'PHX'},
  {'characterName': 'clive', 'name': 'WOL'},
  {'characterName': 'clive', 'name': 'GAR'},
  {'characterName': 'devil-jin', 'name': 'MCR'},
  {'characterName': 'devil-jin', 'name': 'FLY'},
  {'characterName': 'devil-jin', 'name': 'CD'},
  {'characterName': 'dragunov', 'name': 'SNK'},
  {'characterName': 'eddy', 'name': 'RLX'},
  {'characterName': 'eddy', 'name': 'HSP'},
  {'characterName': 'fahkumram', 'name': 'RAM'},
  {'characterName': 'fahkumram', 'name': 'GAR'},
  {'characterName': 'feng', 'name': 'STC'},
  {'characterName': 'feng', 'name': 'BKP'},
  {'characterName': 'feng', 'name': 'BT'},
  {'characterName': 'heihachi', 'name': 'RAI'},
  {'characterName': 'heihachi', 'name': 'FUJ'},
  {'characterName': 'heihachi', 'name': 'WGK'},
  {'characterName': 'heihachi', 'name': 'TGK'},
  {'characterName': 'hwoarang', 'name': 'LFS'},
  {'characterName': 'hwoarang', 'name': 'RFS'},
  {'characterName': 'hwoarang', 'name': 'RFF'},
  {'characterName': 'hwoarang', 'name': 'LFF'},
  {'characterName': 'jack-8', 'name': 'GMH'},
  {'characterName': 'jack-8', 'name': 'SIT'},
  {'characterName': 'jack-8', 'name': 'GMC'},
  {'characterName': 'jin', 'name': 'ZEN'},
  {'characterName': 'jin', 'name': 'CD'},
  {'characterName': 'jun', 'name': 'IZU'},
  {'characterName': 'jun', 'name': 'GEN'},
  {'characterName': 'jun', 'name': 'MIA'},
  {'characterName': 'kazuya', 'name': 'CD'},
  {'characterName': 'king', 'name': 'JAG'},
  {'characterName': 'king', 'name': 'JGC'},
  {'characterName': 'king', 'name': 'ISW'},
  {'characterName': 'king', 'name': 'GS'},
  {'characterName': 'kuma', 'name': 'HBS'},
  {'characterName': 'kuma', 'name': 'SIT'},
  {'characterName': 'kuma', 'name': 'ROLL'},
  {'characterName': 'lars', 'name': 'DEN'},
  {'characterName': 'lars', 'name': 'SEN'},
  {'characterName': 'lars', 'name': 'LEN'},
  {'characterName': 'law', 'name': 'DSS'},
  {'characterName': 'lee', 'name': 'HMS'},
  {'characterName': 'leroy', 'name': 'HRM'},
  {'characterName': 'lidia', 'name': 'HAE'},
  {'characterName': 'lidia', 'name': 'CAT'},
  {'characterName': 'lidia', 'name': 'WLF'},
  {'characterName': 'lidia', 'name': 'HRS'},
  {'characterName': 'lili', 'name': 'DEW'},
  {'characterName': 'lili', 'name': 'RAB'},
  {'characterName': 'lili', 'name': 'BT'},
  {'characterName': 'nina', 'name': 'CD'},
  {'characterName': 'nina', 'name': 'SWA'},
  {'characterName': 'panda', 'name': 'HBS'},
  {'characterName': 'paul', 'name': 'DPD'},
  {'characterName': 'paul', 'name': 'SWA'},
  {'characterName': 'raven', 'name': 'SZN'},
  {'characterName': 'raven', 'name': 'BT'},
  {'characterName': 'reina', 'name': 'WRA'},
  {'characterName': 'reina', 'name': 'SEN'},
  {'characterName': 'reina', 'name': 'UNS'},
  {'characterName': 'reina', 'name': 'CD'},
  {'characterName': 'shaheen', 'name': 'SNK'},
  {'characterName': 'steve', 'name': 'PAB'},
  {'characterName': 'steve', 'name': 'FLK'},
  {'characterName': 'steve', 'name': 'DCK'},
  {'characterName': 'steve', 'name': 'EXT'},
  {'characterName': 'steve', 'name': 'SWY'},
  {'characterName': 'steve', 'name': 'LNH'},
  {'characterName': 'victor', 'name': 'PRF'},
  {'characterName': 'victor', 'name': 'IAI'},
  {'characterName': 'yoshimitsu', 'name': 'FLE'},
  {'characterName': 'yoshimitsu', 'name': 'CD'},
  {'characterName': 'xiaoyu', 'name': 'AOP'},
  {'characterName': 'xiaoyu', 'name': 'RDS'},
  {'characterName': 'xiaoyu', 'name': 'HYP'},
  {'characterName': 'yoshimitsu', 'name': 'NSS'},
  {'characterName': 'yoshimitsu', 'name': 'BT'},
  {'characterName': 'yoshimitsu', 'name': 'KIN'},
  {'characterName': 'yoshimitsu', 'name': 'MED'},
  {'characterName': 'yoshimitsu', 'name': 'IND'},
  {'characterName': 'yoshimitsu', 'name': 'DGF'},
  {'characterName': 'yoshimitsu', 'name': 'FLEA'},
  {'characterName': 'zafina', 'name': 'SCR'},
  {'characterName': 'zafina', 'name': 'MNT'},
  {'characterName': 'zafina', 'name': 'TRT'},
  {'characterName': 'miary-zo', 'name': 'MMO'},
  {'characterName': 'miary-zo', 'name': 'KMH'},
];