// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMbhv85xQkimHvF2M9yobm_6CPRJtZxdY',
    appId: '1:220025240484:web:df48651c2e39b0c8b11f31',
    messagingSenderId: '220025240484',
    projectId: 'tekkencheatsheet-e7c89',
    authDomain: 'tekkencheatsheet-e7c89.firebaseapp.com',
    storageBucket: 'tekkencheatsheet-e7c89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzeranlg68VaKevMynOcJ22dchH97QASk',
    appId: '1:220025240484:android:e18b4968062c2cb4b11f31',
    messagingSenderId: '220025240484',
    projectId: 'tekkencheatsheet-e7c89',
    storageBucket: 'tekkencheatsheet-e7c89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDktcu5CQNdsJrF2JNBP3AQJS8DH102pYc',
    appId: '1:220025240484:ios:62edc43b45824ad1b11f31',
    messagingSenderId: '220025240484',
    projectId: 'tekkencheatsheet-e7c89',
    storageBucket: 'tekkencheatsheet-e7c89.firebasestorage.app',
    iosBundleId: 'com.example.tekkenCheatSheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDktcu5CQNdsJrF2JNBP3AQJS8DH102pYc',
    appId: '1:220025240484:ios:62edc43b45824ad1b11f31',
    messagingSenderId: '220025240484',
    projectId: 'tekkencheatsheet-e7c89',
    storageBucket: 'tekkencheatsheet-e7c89.firebasestorage.app',
    iosBundleId: 'com.example.tekkenCheatSheet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMbhv85xQkimHvF2M9yobm_6CPRJtZxdY',
    appId: '1:220025240484:web:ee7e53f3a2a0202cb11f31',
    messagingSenderId: '220025240484',
    projectId: 'tekkencheatsheet-e7c89',
    authDomain: 'tekkencheatsheet-e7c89.firebaseapp.com',
    storageBucket: 'tekkencheatsheet-e7c89.firebasestorage.app',
  );
}
